### ISSUE TITLE
Get a reasonable python workflow

### ISSUE THREAD

**Issue by alanchrt** [alanctkc/dotfiles#125]
Virtualenv may not be an option, and `nix-shell` could be the only alternative:

https://nixos.wiki/wiki/Python#Emulating_virtualenv_with_nix-shell

But, spacemacs has automatic virtualenv/pyenv detection. Maybe it will need to be rewired like this:

https://github.com/syl20bnr/spacemacs/issues/7404#issuecomment-254017887

**Comment by alanctkc** [comment]
https://www.reddit.com/r/NixOS/comments/732765/nixos_python_3_pip_gunicorn_nginx_best_practices/

**Comment by alanctkc** [comment]
Make sure zsh theme and spacemacs/anaconda work still!

**Comment by alanctkc** [comment]
Make sure all python deps needed by python layer are present somehow:

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/python

**Comment by alanctkc** [comment]
Possibly will need this on occasion--

https://github.com/garbas/pypi2nix

**Comment by alanchrt** [comment]
:wave: NixOS was fun, on Fedora now.
