### ISSUE TITLE
Investigate macbook battery

### ISSUE THREAD

**Issue by alanct-minted** [alanctkc/dotfiles#32]
Possibly http://askubuntu.com/a/158906

**Comment by alanct-minted** [comment]
`bcmwl-kernel-source` may already install the proprietary (STA) wifi driver

**Comment by alanct-minted** [comment]
disabling bluetooth looks promising: http://askubuntu.com/a/2568

**Comment by alanct-minted** [comment]
https://help.ubuntu.com/community/PowerManagement/ReducedPower#Using_less_power_with_laptop-mode-tools

**Comment by alanctkc** [comment]
No more macbook
